services:
  server:
    build: .
    env_file:
      - .env
    volumes:
      - ./ssl:/app/ssl
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: unless-stopped
  redis:
    image: redis:alpine
    command: redis-server
    restart: unless-stopped
