services:
  server:
    build: bddvlpr/untis-ics-sync:latest
    env_file:
      - .env
    environment:
      - ENABLE_HTTP=true
      - ENABLE_HTTPS=true
    volumes:
      - ./ssl:/app/ssl
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  redis:
    image: redis:alpine
    command: redis-server
    restart: unless-stopped
