services:
  server:
    build: .
    env_file:
      - .env
    volumes:
      - ./ssl:/app/ssl
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  redis:
    image: redis:alpine
    command: redis-server
    restart: unless-stopped
