name: Docker CD
on: [tag]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: untis-ics-sync
jobs:
  build-and-push:
    name: Build Docker image and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      package: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@3
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
